### ISSUE TITLE
Export drawing add Black line on image

### ISSUE THREAD

**Issue by ArgonTech** [Raed-Mughaus/DrawingView#10]
when i am exporting Drawing from drawing view, it shows a black line on top of view. Please see attached:
![Screenshot 2019-07-26 at 11 46 22 AM](https://user-images.githubusercontent.com/52270923/61931809-2cec8300-af9b-11e9-8392-a5001c55bc4f.png)

**Comment by Raed-Mughaus** [comment]
Could you post your code?
