### ISSUE TITLE
Drawing is lost when out of focus

### ISSUE THREAD

**Issue by alemoreirac** [Raed-Mughaus/DrawingView#2]
I'm very happy with this API at first glance, it responds really well and the code's neat.

I noticed that when the application loses focus, the drawing is lost. It has any code workaround? Made a video of the issue.

[mobizen_20180612_092917.zip](https://github.com/Raed-Mughaus/DrawingView/files/2094059/mobizen_20180612_092917.zip)

**Comment by Raed-Mughaus** [comment]
Could you tell me where do you call drawingView.setBackgroundImage(Bitmap) ?
Because calling this method clears any previous drawing.

**Comment by alemoreirac** [comment]
I was calling the setBackgroundImage on the onWindowFocusChanged (my bad);

First I was using the onCreate method, but my view wasn't ready at that time (throwing **.IllegalArgumentException: width and height must be > 0**)

Then I realized that i should call:

` drawingView.post(new Runnable() {
            @Override
            public void run() {
                drawingView.setBackgroundImage(icon);
            }
        });
`
If there's an easier/smartest workaround please put that on the api example.

Thank you Raed!

**Comment by alemoreirac** [comment]
I was calling the setBackgroundImage on the onWindowFocusChanged (my bad);

First I was using the onCreate method, but my view wasn't ready at that time (throwing **.IllegalArgumentException: width and height must be > 0**)

Then I realized that i should call:

` drawingView.post(new Runnable() {
            @Override
            public void run() {
                drawingView.setBackgroundImage(icon);
            }
        });
`
If there's an easier/smartest workaround please put that on the api example.

Thank you Raed!

**Comment by Raed-Mughaus** [comment]
An update has been released to fix the issue, the new verison is "1.3.0". Now you should be able to set the background anywhere. 
Please keep helping me by opening an issue about any error you find in DrawingView.
